_.json_encoder  # unused attribute (cloud-server/src/app/__init__.py:15)
qty  # unused variable (cloud-server/src/app/types/orders.py:28)
time_in_force  # unused variable (cloud-server/src/app/types/orders.py:29)
select  # unused import (cloud-server/src/main.py:1)
select  # unused import (server/main.py:1)
_.getOpenOrders  # unused method (cloud-server/src/app/main/modules/Trades.py:67)
_.getPosition  # unused method (cloud-server/src/app/main/modules/Trades.py:48)