_.json_encoder  # unused attribute (server/src/app/__init__.py:16)
qty  # unused variable (server/src/app/types/orders.py:28)
time_in_force  # unused variable (server/src/app/types/orders.py:29)
select  # unused import (server/src/main.py:1)
_.getOpenOrders  # unused method (server/src/app/main/modules/Trades.py:67)
_.getPosition  # unused method (server/src/app/main/modules/Trades.py:48)
CompleteTaskCommand  # unused class (server/src/app/main/modules/commands/taskCommands/CompleteTaskCommand.py:4)
