version: '3.4'

x-server:
  &default-server
  image: 549896682433.dkr.ecr.us-west-2.amazonaws.com/mira:latest
  build: 
    context: ../
    dockerfile: ./production/serverConfig/Dockerfile.Server
  container_name: server
  platform: "linux/amd64"

x-local-server:
  &default-local-server
  image: 549896682433.dkr.ecr.us-west-2.amazonaws.com/mira-local-server:latest
  build: 
    context: ../
    dockerfile: ./production/localServerConfig/Dockerfile.LocalServer
  container_name: local-server
  privileged: true


services:
  server:
    *default-server
  
  server-version:
    << : *default-server
    image: 549896682433.dkr.ecr.us-west-2.amazonaws.com/mira:0.0.0

  local-server:
    *default-local-server
    

  local-server-version:
    << : *default-local-server
    image: 549896682433.dkr.ecr.us-west-2.amazonaws.com/mira-local-server:0.0.0
  





