version: '3.4'

x-server:
  &default-server
  image: 549896682433.dkr.ecr.us-west-2.amazonaws.com/mira:latest
  build: 
    context: ../
    dockerfile: ./production/serverConfig/Dockerfile.Server
  container_name: server
  platform: "linux/amd64"


services:
  server:
    *default-server
  
  server-version:
    << : *default-server
    image: 549896682433.dkr.ecr.us-west-2.amazonaws.com/mira:0.0.0

    

  





